### ISSUE TITLE
No decoy in my peptides.csv using PeaksDB as search engine

### ISSUE THREAD

**Issue by punching-samuel** [QuantSysBio/inSPIRE#32]
Peaks is a non-open source software, and its decoy algorithm is not public. The result table Peaks exports does not include fake peptides. If I do not add some known non-sample peptides, is there no way to use inSPIRE rescore? 

With regards,
Samuel

**Comment by punching-samuel** [comment]
![Uploading 截屏2024-06-29 00.11.01.png…]()

**Comment by punching-samuel** [comment]
<img width="957" alt="截屏2024-06-29 00 11 01" src="https://github.com/QuantSysBio/inSPIRE/assets/165863420/d7be1691-e1f4-4854-9483-365cd31c5853">

**Comment by punching-samuel** [comment]
The core of the tool percolator utilizes supervised SVM (Support Vector Machine). Perhaps these decoy peptides are required to be present? However, I did not add any standard peptides in my immunopeptidomics experiment.

**Comment by jamc1996** [comment]
Hi Samuel,

Thanks for using inSPIRE. We actually just wrote a markdown guide for how to use PEAKS with inSPIRE:

https://github.com/QuantSysBio/inSPIRE/blob/main/docs/peaks_exports.md

The problem could be that you didn't select use decoy-fusion in the search, in which case you would need to rerun your PEAKS search but it could also just be that you are not displaying decoys (see the 4th and 5th images in the guide above) in which case you would just need to re-export your results.

One more thing, you should also probably use "DB search psm.csv" peaks export rather than peptides.csv file as inSPIRE will do better rescoring all PSMs.

Hope this helps!

Best wishes,
John.

**Comment by punching-samuel** [comment]
> Hi Samuel,
> 
> Thanks for using inSPIRE. We actually just wrote a markdown guide for how to use PEAKS with inSPIRE:
> 
> https://github.com/QuantSysBio/inSPIRE/blob/main/docs/peaks_exports.md
> 
> The problem could be that you didn't select use decoy-fusion in the search, in which case you would need to rerun your PEAKS search but it could also just be that you are not displaying decoys (see the 4th and 5th images in the guide above) in which case you would just need to re-export your results.
> 
> One more thing, you should also probably use "DB search psm.csv" peaks export rather than peptides.csv file as inSPIRE will do better rescoring all PSMs.
> 
> Hope this helps!
> 
> Best wishes, John.

It sounds credible. My table peptides.csv also contains the content that inSPIRE needs to provide, although there is a problem in the final rescore stage. Perhaps you can upload or show some examples of input tables if choose the Peaks search engine?

Best wishes,
Yang

**Comment by punching-samuel** [comment]
> Hi Samuel,
> 
> Thanks for using inSPIRE. We actually just wrote a markdown guide for how to use PEAKS with inSPIRE:
> 
> https://github.com/QuantSysBio/inSPIRE/blob/main/docs/peaks_exports.md
> 
> The problem could be that you didn't select use decoy-fusion in the search, in which case you would need to rerun your PEAKS search but it could also just be that you are not displaying decoys (see the 4th and 5th images in the guide above) in which case you would just need to re-export your results.
> 
> One more thing, you should also probably use "DB search psm.csv" peaks export rather than peptides.csv file as inSPIRE will do better rescoring all PSMs.
> 
> Hope this helps!
> 
> Best wishes, John.

It sounds credible. My table peptides.csv also contains the content that inSPIRE needs to provide, although there is a problem in the final rescore stage. Perhaps you can upload or show some examples of input tables if choose the Peaks search engine?

Best wishes,
Samuel

**Comment by jamc1996** [comment]
Thanks, I've added an extra screenshot in the docs now to show the tables needed:

https://github.com/QuantSysBio/inSPIRE/blob/main/docs/peaks_exports.md

Let me know if you still have problems 👍
